version: "3"
services:
  mysql:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: othello
      MYSQL_USER: othello_user
      MYSQL_PASSWORD: pass
